[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
luck_distributor = "G8hKTeAbpMCwNTn7WzKnT6PFxnVfLJuvQFg5XBTX2E8e"

[programs.mainnet]
luck_distributor = "G8hKTeAbpMCwNTn7WzKnT6PFxnVfLJuvQFg5XBTX2E8e"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test --manifest-path programs/luck-distributor/Cargo.toml"
